"""
export_azure.py
---------------
Exports the built SQLite database (kh222.db) into Azure-SQL-ready assets:

  * csv_clean/<table>.csv    - one UTF-8 CSV per table (header + data)
  * schema_azure_sql.sql     - idempotent T-SQL CREATE TABLE / INDEX / FK / VIEW
  * load_azure.sql           - TRUNCATE + BULK INSERT template per table

Usage:
    python export_azure.py [--db kh222.db] [--out .]
"""

from __future__ import annotations

import argparse
import csv
import os
import shutil
import sqlite3
from pathlib import Path

# ---------------------------------------------------------------
# SQLite -> Azure SQL (T-SQL) type mapping.
# ---------------------------------------------------------------

BIGINT_COLS = {"idn", "victim_idn", "victim_2_idn", "victim_3_idn"}
MONEY_COLS  = {"bond_amount", "total_paid", "payment_amount"}
BIT_COLS    = {
    "dma", "gps", "paid", "ptr_successfully_completed",
    "victim_accept_deny_gps", "da_emailed", "attachments", "comments",
}
NOTES_COLS  = {"bond_conditions"}
WIDE_TEXT_COLS = {
    "defendant", "defendant_name", "defendant_last_name",
    "victim", "victim_2", "victim_3",
    "case_number", "warrant_case_num", "link_to_files", "name",
}
DATE_COLS   = {
    "referral_date", "payment_date", "date", "check_in_date",
    "birthdate", "created", "modified", "closed_date",
    "recevied_signed_copy_date", "contact_date", "released_to_hilltop_date",
    "victim_time_48", "gps_install_date",
}

PK_OVERRIDES = {
    "raw_payments":     ("payment_id",  "BIGINT IDENTITY(1,1) PRIMARY KEY"),
    "raw_check_ins":    ("check_in_id", "BIGINT IDENTITY(1,1) PRIMARY KEY"),
    "raw_gps_48_hours": ("gps_id",      "BIGINT IDENTITY(1,1) PRIMARY KEY"),
    "payments":         ("payment_id",  "BIGINT IDENTITY(1,1) PRIMARY KEY"),
    "check_ins":        ("check_in_id", "BIGINT IDENTITY(1,1) PRIMARY KEY"),
    "gps_events":       ("gps_id",      "BIGINT IDENTITY(1,1) PRIMARY KEY"),
    "cases":            ("case_id",     "BIGINT IDENTITY(1,1) PRIMARY KEY"),
    "defendants":       ("idn",         "BIGINT PRIMARY KEY"),
}

FKS = [
    ("cases",      "idn", "defendants", "idn"),
    ("payments",   "idn", "defendants", "idn"),
    ("check_ins",  "idn", "defendants", "idn"),
    ("gps_events", "idn", "defendants", "idn"),
]

INDEXES = [
    ("idx_cases_idn",     "cases",      ["idn"]),
    ("idx_cases_case",    "cases",      ["case_number"]),
    ("idx_payments_idn",  "payments",   ["idn"]),
    ("idx_payments_date", "payments",   ["payment_date"]),
    ("idx_checkins_idn",  "check_ins",  ["idn"]),
    ("idx_checkins_date", "check_ins",  ["check_in_date"]),
    ("idx_gps_idn",       "gps_events", ["idn"]),
]


def azure_col_type(table, col, sqlite_type):
    pk_col, pk_decl = PK_OVERRIDES.get(table, (None, None))
    if col == pk_col:
        return pk_decl
    if col in BIGINT_COLS: return "BIGINT NULL"
    if col in MONEY_COLS:  return "DECIMAL(18,2) NULL"
    if col in BIT_COLS:    return "BIT NULL"
    if col in NOTES_COLS:  return "NVARCHAR(MAX) NULL"
    if col in DATE_COLS:   return "NVARCHAR(50) NULL"
    if col in WIDE_TEXT_COLS: return "NVARCHAR(1000) NULL"
    t = (sqlite_type or "").upper()
    if "INT" in t: return "BIGINT NULL"
    if "REAL" in t or "FLOA" in t or "DOUB" in t or "NUMERIC" in t:
        return "DECIMAL(18,2) NULL"
    return "NVARCHAR(500) NULL"


def fetch_tables(con):
    return [r[0] for r in con.execute(
        "SELECT name FROM sqlite_master "
        "WHERE type='table' AND name NOT LIKE 'sqlite_%' "
        "ORDER BY CASE WHEN name LIKE 'raw_%' THEN 0 ELSE 1 END, name"
    )]


def fetch_columns(con, table):
    return [(r[1], r[2]) for r in con.execute(f"PRAGMA table_info({table})")]


def export_csvs(con, csv_dir):
    csv_dir.mkdir(parents=True, exist_ok=True)
    counts = {}
    for table in fetch_tables(con):
        cols = [c for c, _ in fetch_columns(con, table)]
        cur = con.cursor()
        quoted = ",".join(f'"{c}"' for c in cols)
        cur.execute(f'SELECT {quoted} FROM "{table}"')
        out = csv_dir / f"{table}.csv"
        with out.open("w", encoding="utf-8", newline="") as fh:
            w = csv.writer(fh, quoting=csv.QUOTE_MINIMAL)
            w.writerow(cols)
            n = 0
            for row in cur:
                w.writerow(["" if v is None else v for v in row])
                n += 1
        counts[table] = n
    return counts


def write_schema_sql(con, out):
    tables = fetch_tables(con)
    L = []
    L.append("-- =====================================================")
    L.append("-- KH222 Pre-Trial Schema - Azure SQL Database / SQL Server 2016+")
    L.append("-- Generated by export_azure.py (re-runnable).")
    L.append("-- =====================================================\n")

    L.append("IF OBJECT_ID('dbo.v_defendant_summary', 'V') IS NOT NULL DROP VIEW dbo.v_defendant_summary;")
    L.append("GO\n")

    drop_order = [
        "cases", "payments", "check_ins", "gps_events", "defendants",
        "raw_blue_book", "raw_master_list",
        "raw_payments", "raw_check_ins", "raw_gps_48_hours",
    ]
    L.append("-- ---- Drop tables (child-first) ----")
    for t in drop_order:
        L.append(f"IF OBJECT_ID('dbo.{t}', 'U') IS NOT NULL DROP TABLE dbo.{t};")
    L.append("GO\n")

    for t in reversed(drop_order):
        if t not in tables:
            continue
        L.append(f"-- ---- {t} ----")
        L.append(f"CREATE TABLE dbo.{t} (")
        cl = []
        for col, sqlt in fetch_columns(con, t):
            cl.append(f"    [{col}] {azure_col_type(t, col, sqlt)}")
        L.append(",\n".join(cl))
        L.append(");")
        L.append("GO\n")

    L.append("-- ---- Foreign keys ----")
    for child, cc, parent, pc in FKS:
        L.append(
            f"ALTER TABLE dbo.{child} ADD CONSTRAINT fk_{child}_{cc}_{parent} "
            f"FOREIGN KEY ([{cc}]) REFERENCES dbo.{parent}([{pc}]);"
        )
    L.append("GO\n")

    L.append("-- ---- Indexes ----")
    for name, table, cols in INDEXES:
        cl = ", ".join(f"[{c}]" for c in cols)
        L.append(f"CREATE INDEX {name} ON dbo.{table} ({cl});")
    L.append("GO\n")

    L.append("-- ---- Summary view ----")
    L.append("CREATE VIEW dbo.v_defendant_summary AS")
    L.append("SELECT d.idn, d.defendant_name, d.defendant_last_name, d.pretrial_level,")
    L.append("       d.charge_type, d.case_status, d.supervising_officer,")
    L.append("       d.referral_date, d.closed_date,")
    L.append("       (SELECT COUNT(*) FROM dbo.cases c      WHERE c.idn = d.idn)   AS case_count,")
    L.append("       (SELECT COUNT(*) FROM dbo.check_ins ci WHERE ci.idn = d.idn)  AS check_in_count,")
    L.append("       (SELECT COUNT(*) FROM dbo.payments p   WHERE p.idn = d.idn)   AS payment_count,")
    L.append("       (SELECT COALESCE(SUM(p.payment_amount),0) FROM dbo.payments p WHERE p.idn = d.idn) AS total_paid_calc,")
    L.append("       (SELECT COUNT(*) FROM dbo.gps_events g WHERE g.idn = d.idn)   AS gps_events_count")
    L.append("FROM dbo.defendants d;")
    L.append("GO\n")

    out.write_text("\n".join(L), encoding="utf-8")


def write_load_sql(tables, out):
    L = []
    L.append("-- =====================================================")
    L.append("-- KH222 Pre-Trial  -  BULK INSERT loader template")
    L.append("-- =====================================================\n")
    L.append("/* ---- Azure Blob setup (uncomment + fill in, run once) ----")
    L.append("CREATE MASTER KEY ENCRYPTION BY PASSWORD = '<strong-password>';")
    L.append("GO")
    L.append("")
    L.append("CREATE DATABASE SCOPED CREDENTIAL kh222_blob_cred")
    L.append("    WITH IDENTITY = 'SHARED ACCESS SIGNATURE',")
    L.append("    SECRET = '<sas-token-without-leading-?>';")
    L.append("GO")
    L.append("")
    L.append("CREATE EXTERNAL DATA SOURCE kh222_blob")
    L.append("    WITH (TYPE = BLOB_STORAGE,")
    L.append("          LOCATION = 'https://<account>.blob.core.windows.net/<container>',")
    L.append("          CREDENTIAL = kh222_blob_cred);")
    L.append("GO")
    L.append("---- end Azure Blob setup ---- */\n")

    trunc_order = [
        "cases", "payments", "check_ins", "gps_events", "defendants",
        "raw_blue_book", "raw_master_list",
        "raw_payments", "raw_check_ins", "raw_gps_48_hours",
    ]
    L.append("-- Truncate child-first.")
    for t in trunc_order:
        if t in tables:
            L.append(f"TRUNCATE TABLE dbo.{t};")
    L.append("GO\n")

    for t in reversed(trunc_order):
        if t not in tables:
            continue
        L.append(f"-- ---- Load {t} ----")
        L.append(f"BULK INSERT dbo.{t}")
        L.append(f"FROM 'csv_clean/{t}.csv'  -- or DATA_SOURCE = 'kh222_blob', 'csv_clean/{t}.csv'")
        L.append("WITH (")
        L.append("    FORMAT = 'CSV',")
        L.append("    FIRSTROW = 2,")
        L.append("    FIELDTERMINATOR = ',',")
        L.append("    ROWTERMINATOR = '0x0a',")
        L.append("    CODEPAGE = '65001',")
        L.append("    FIELDQUOTE = '\"',")
        L.append("    TABLOCK")
        L.append(");")
        L.append("GO\n")

    L.append("-- ---- Post-load row-count sanity ----")
    L.append("SELECT 'raw_master_list' AS tbl, COUNT(*) FROM dbo.raw_master_list  UNION ALL")
    L.append("SELECT 'raw_blue_book',         COUNT(*) FROM dbo.raw_blue_book    UNION ALL")
    L.append("SELECT 'raw_payments',          COUNT(*) FROM dbo.raw_payments     UNION ALL")
    L.append("SELECT 'raw_check_ins',         COUNT(*) FROM dbo.raw_check_ins    UNION ALL")
    L.append("SELECT 'raw_gps_48_hours',      COUNT(*) FROM dbo.raw_gps_48_hours UNION ALL")
    L.append("SELECT 'defendants',            COUNT(*) FROM dbo.defendants       UNION ALL")
    L.append("SELECT 'cases',                 COUNT(*) FROM dbo.cases            UNION ALL")
    L.append("SELECT 'payments',              COUNT(*) FROM dbo.payments         UNION ALL")
    L.append("SELECT 'check_ins',             COUNT(*) FROM dbo.check_ins        UNION ALL")
    L.append("SELECT 'gps_events',            COUNT(*) FROM dbo.gps_events;")
    L.append("GO")

    out.write_text("\n".join(L), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db",  default=os.environ.get("KH222_DB",  "kh222.db"))
    ap.add_argument("--out", default=os.environ.get("KH222_OUT", "."))
    args = ap.parse_args()

    db_path = Path(args.db).resolve()
    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    # Stage in /tmp; OneDrive mounts can't lock SQLite.
    stage = Path("/tmp/kh222_export_stage")
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)
    csv_stage = stage / "csv_clean"
    csv_stage.mkdir()

    con = sqlite3.connect(db_path)
    try:
        counts = export_csvs(con, csv_stage)
        write_schema_sql(con, stage / "schema_azure_sql.sql")
        tables = fetch_tables(con)
        write_load_sql(tables, stage / "load_azure.sql")
    finally:
        con.close()

    target_csv = out_dir / "csv_clean"
    target_csv.mkdir(parents=True, exist_ok=True)
    for p in csv_stage.iterdir():
        shutil.copy(p, target_csv / p.name)
    shutil.copy(stage / "schema_azure_sql.sql", out_dir / "schema_azure_sql.sql")
    shutil.copy(stage / "load_azure.sql",       out_dir / "load_azure.sql")

    print("Exported CSVs:")
    for t, n in counts.items():
        print(f"  {t}: {n:>7,} rows")


if __name__ == "__main__":
    main()
