-- =====================================================
-- KH222 Pre-Trial Schema - Azure SQL Database / SQL Server 2016+
-- Generated by export_azure.py (re-runnable).
-- =====================================================

IF OBJECT_ID('dbo.v_defendant_summary', 'V') IS NOT NULL DROP VIEW dbo.v_defendant_summary;
GO

-- ---- Drop tables (child-first) ----
IF OBJECT_ID('dbo.cases', 'U') IS NOT NULL DROP TABLE dbo.cases;
IF OBJECT_ID('dbo.payments', 'U') IS NOT NULL DROP TABLE dbo.payments;
IF OBJECT_ID('dbo.check_ins', 'U') IS NOT NULL DROP TABLE dbo.check_ins;
IF OBJECT_ID('dbo.gps_events', 'U') IS NOT NULL DROP TABLE dbo.gps_events;
IF OBJECT_ID('dbo.defendants', 'U') IS NOT NULL DROP TABLE dbo.defendants;
IF OBJECT_ID('dbo.raw_blue_book', 'U') IS NOT NULL DROP TABLE dbo.raw_blue_book;
IF OBJECT_ID('dbo.raw_master_list', 'U') IS NOT NULL DROP TABLE dbo.raw_master_list;
IF OBJECT_ID('dbo.raw_payments', 'U') IS NOT NULL DROP TABLE dbo.raw_payments;
IF OBJECT_ID('dbo.raw_check_ins', 'U') IS NOT NULL DROP TABLE dbo.raw_check_ins;
IF OBJECT_ID('dbo.raw_gps_48_hours', 'U') IS NOT NULL DROP TABLE dbo.raw_gps_48_hours;
GO

-- ---- raw_gps_48_hours ----
CREATE TABLE dbo.raw_gps_48_hours (
    [gps_id] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [referral_date] NVARCHAR(50) NULL,
    [defendant] NVARCHAR(1000) NULL,
    [idn] BIGINT NULL,
    [case_number] NVARCHAR(1000) NULL,
    [gps_type] NVARCHAR(500) NULL,
    [case_status] NVARCHAR(500) NULL,
    [paid] BIT NULL,
    [victim] NVARCHAR(1000) NULL,
    [victim_idn] BIGINT NULL,
    [victim_time_48] NVARCHAR(50) NULL,
    [victim_accept_deny_gps] BIT NULL,
    [gps_install_date] NVARCHAR(50) NULL,
    [order] NVARCHAR(500) NULL,
    [da_emailed] BIT NULL,
    [closed_date] NVARCHAR(50) NULL,
    [victim_2] NVARCHAR(1000) NULL,
    [victim_2_idn] BIGINT NULL,
    [victim_3] NVARCHAR(1000) NULL,
    [victim_3_idn] BIGINT NULL
);
GO

-- ---- raw_check_ins ----
CREATE TABLE dbo.raw_check_ins (
    [check_in_id] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [case_number] NVARCHAR(1000) NULL,
    [idn] BIGINT NULL,
    [defendant] NVARCHAR(1000) NULL,
    [date] NVARCHAR(50) NULL,
    [type_of_check_in] NVARCHAR(500) NULL,
    [supervising_officer] NVARCHAR(500) NULL,
    [case_status] NVARCHAR(500) NULL,
    [referral_date] NVARCHAR(50) NULL,
    [pretrial_level] BIGINT NULL
);
GO

-- ---- raw_payments ----
CREATE TABLE dbo.raw_payments (
    [payment_id] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [case_number] NVARCHAR(1000) NULL,
    [defendant] NVARCHAR(1000) NULL,
    [idn] BIGINT NULL,
    [payment_date] NVARCHAR(50) NULL,
    [payment_amount] DECIMAL(18,2) NULL,
    [officer_that_collected_payment] NVARCHAR(500) NULL,
    [payment_type] NVARCHAR(500) NULL,
    [case_status] NVARCHAR(500) NULL
);
GO

-- ---- raw_master_list ----
CREATE TABLE dbo.raw_master_list (
    [defendant_last_name] NVARCHAR(1000) NULL,
    [idn] BIGINT NULL,
    [pretrial_level] BIGINT NULL,
    [referral_date] NVARCHAR(50) NULL,
    [charge_type] NVARCHAR(500) NULL,
    [order_from] NVARCHAR(500) NULL,
    [supervision_type] NVARCHAR(500) NULL,
    [dma] BIT NULL
);
GO

-- ---- raw_blue_book ----
CREATE TABLE dbo.raw_blue_book (
    [defendant] NVARCHAR(1000) NULL,
    [idn] BIGINT NULL,
    [warrant_case_num] NVARCHAR(1000) NULL,
    [idn_lookup] NVARCHAR(500) NULL,
    [pretrial_level] BIGINT NULL,
    [referral_date] NVARCHAR(50) NULL,
    [supervision_type] NVARCHAR(500) NULL,
    [comments] BIT NULL,
    [gps] BIT NULL,
    [bond_conditions] NVARCHAR(MAX) NULL,
    [bond_amount] DECIMAL(18,2) NULL,
    [charge_type] NVARCHAR(500) NULL,
    [order_from] NVARCHAR(500) NULL,
    [recevied_signed_copy_date] NVARCHAR(50) NULL,
    [contact_date] NVARCHAR(50) NULL,
    [released_to_hilltop_date] NVARCHAR(50) NULL,
    [victim] NVARCHAR(1000) NULL,
    [victim_idn] BIGINT NULL,
    [victim_time_48] NVARCHAR(50) NULL,
    [victim_2] NVARCHAR(1000) NULL,
    [victim_2_idn] BIGINT NULL,
    [victim_3] NVARCHAR(1000) NULL,
    [victim_3_idn] BIGINT NULL,
    [created] NVARCHAR(50) NULL,
    [link_to_files] NVARCHAR(1000) NULL,
    [blank] NVARCHAR(500) NULL,
    [modified] NVARCHAR(50) NULL,
    [created_by] NVARCHAR(500) NULL,
    [attachments] BIT NULL,
    [modified_by] NVARCHAR(500) NULL,
    [dma] BIT NULL,
    [gps_type] NVARCHAR(500) NULL,
    [birthdate] NVARCHAR(50) NULL,
    [name] NVARCHAR(1000) NULL,
    [supervising_officer] NVARCHAR(500) NULL,
    [case_status] NVARCHAR(500) NULL,
    [closed_date] NVARCHAR(50) NULL,
    [ptr_successfully_completed] BIT NULL,
    [day_adjustment] BIGINT NULL,
    [total_paid] DECIMAL(18,2) NULL
);
GO

-- ---- defendants ----
CREATE TABLE dbo.defendants (
    [idn] BIGINT PRIMARY KEY,
    [defendant_name] NVARCHAR(1000) NULL,
    [defendant_last_name] NVARCHAR(1000) NULL,
    [birthdate] NVARCHAR(50) NULL,
    [pretrial_level] BIGINT NULL,
    [charge_type] NVARCHAR(500) NULL,
    [supervision_type] NVARCHAR(500) NULL,
    [order_from] NVARCHAR(500) NULL,
    [dma] BIT NULL,
    [gps] BIT NULL,
    [referral_date] NVARCHAR(50) NULL,
    [closed_date] NVARCHAR(50) NULL,
    [case_status] NVARCHAR(500) NULL,
    [supervising_officer] NVARCHAR(500) NULL,
    [ptr_successfully_completed] BIT NULL,
    [bond_amount] DECIMAL(18,2) NULL,
    [total_paid] DECIMAL(18,2) NULL,
    [source] NVARCHAR(500) NULL
);
GO

-- ---- gps_events ----
CREATE TABLE dbo.gps_events (
    [gps_id] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [idn] BIGINT NULL,
    [case_number] NVARCHAR(1000) NULL,
    [defendant] NVARCHAR(1000) NULL,
    [referral_date] NVARCHAR(50) NULL,
    [gps_type] NVARCHAR(500) NULL,
    [case_status] NVARCHAR(500) NULL,
    [paid] BIT NULL,
    [victim] NVARCHAR(1000) NULL,
    [victim_idn] BIGINT NULL,
    [victim_time_48] NVARCHAR(50) NULL,
    [victim_accept_deny_gps] BIT NULL,
    [gps_install_date] NVARCHAR(50) NULL,
    [court_order] NVARCHAR(500) NULL,
    [da_emailed] BIT NULL,
    [closed_date] NVARCHAR(50) NULL
);
GO

-- ---- check_ins ----
CREATE TABLE dbo.check_ins (
    [check_in_id] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [idn] BIGINT NULL,
    [case_number] NVARCHAR(1000) NULL,
    [defendant] NVARCHAR(1000) NULL,
    [check_in_date] NVARCHAR(50) NULL,
    [type_of_check_in] NVARCHAR(500) NULL,
    [supervising_officer] NVARCHAR(500) NULL,
    [case_status] NVARCHAR(500) NULL,
    [referral_date] NVARCHAR(50) NULL,
    [pretrial_level] BIGINT NULL
);
GO

-- ---- payments ----
CREATE TABLE dbo.payments (
    [payment_id] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [idn] BIGINT NULL,
    [case_number] NVARCHAR(1000) NULL,
    [defendant] NVARCHAR(1000) NULL,
    [payment_date] NVARCHAR(50) NULL,
    [payment_amount] DECIMAL(18,2) NULL,
    [officer] NVARCHAR(500) NULL,
    [payment_type] NVARCHAR(500) NULL,
    [case_status] NVARCHAR(500) NULL
);
GO

-- ---- cases ----
CREATE TABLE dbo.cases (
    [case_id] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [idn] BIGINT NULL,
    [case_number] NVARCHAR(1000) NULL,
    [source] NVARCHAR(500) NULL
);
GO

-- ---- Foreign keys ----
ALTER TABLE dbo.cases ADD CONSTRAINT fk_cases_idn_defendants FOREIGN KEY ([idn]) REFERENCES dbo.defendants([idn]);
ALTER TABLE dbo.payments ADD CONSTRAINT fk_payments_idn_defendants FOREIGN KEY ([idn]) REFERENCES dbo.defendants([idn]);
ALTER TABLE dbo.check_ins ADD CONSTRAINT fk_check_ins_idn_defendants FOREIGN KEY ([idn]) REFERENCES dbo.defendants([idn]);
ALTER TABLE dbo.gps_events ADD CONSTRAINT fk_gps_events_idn_defendants FOREIGN KEY ([idn]) REFERENCES dbo.defendants([idn]);
GO

-- ---- Indexes ----
CREATE INDEX idx_cases_idn ON dbo.cases ([idn]);
CREATE INDEX idx_cases_case ON dbo.cases ([case_number]);
CREATE INDEX idx_payments_idn ON dbo.payments ([idn]);
CREATE INDEX idx_payments_date ON dbo.payments ([payment_date]);
CREATE INDEX idx_checkins_idn ON dbo.check_ins ([idn]);
CREATE INDEX idx_checkins_date ON dbo.check_ins ([check_in_date]);
CREATE INDEX idx_gps_idn ON dbo.gps_events ([idn]);
GO

-- ---- Summary view ----
CREATE VIEW dbo.v_defendant_summary AS
SELECT d.idn, d.defendant_name, d.defendant_last_name, d.pretrial_level,
       d.charge_type, d.case_status, d.supervising_officer,
       d.referral_date, d.closed_date,
       (SELECT COUNT(*) FROM dbo.cases c      WHERE c.idn = d.idn)   AS case_count,
       (SELECT COUNT(*) FROM dbo.check_ins ci WHERE ci.idn = d.idn)  AS check_in_count,
       (SELECT COUNT(*) FROM dbo.payments p   WHERE p.idn = d.idn)   AS payment_count,
       (SELECT COALESCE(SUM(p.payment_amount),0) FROM dbo.payments p WHERE p.idn = d.idn) AS total_paid_calc,
       (SELECT COUNT(*) FROM dbo.gps_events g WHERE g.idn = d.idn)   AS gps_events_count
FROM dbo.defendants d;
GO
