package db

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"testing"
	"time"

	"pretrial-knoxc/internal/emfees"
)

// emfees_golden.json is generated by running the canonical "past-due-em-fees"
// skill (scripts/generate_memos.py) against CSVs exported verbatim from the offline
// db/kh222.db, as-of 2026-05-31. This test re-derives the same records through the
// Go port (emfees.Compute via db.EMFees) and asserts they match record-for-record —
// proving the port reproduces the user's "already figured out" methodology exactly.
//
// Regenerate after any intentional methodology change with:
//   .parity-venv\Scripts\python - < (export DB -> CSV, run generate_memos, dump JSON)
// (see the session notes / PHASE_9_EMFEES.md).

type goldenRec struct {
	Kind     string  `json:"kind"`
	IDN      string  `json:"idn"`
	Case     string  `json:"case"`
	Type     string  `json:"type"`
	Days     int     `json:"days"`
	Owed     float64 `json:"owed"`
	Paid     float64 `json:"paid"`
	Behind   float64 `json:"behind"`
	StartSrc string  `json:"start_src"`
}

type goldenFile struct {
	AsOf        string      `json:"as_of"`
	OpenCount   int         `json:"open_count"`
	ClosedCount int         `json:"closed_count"`
	OpenTotal   float64     `json:"open_total"`
	ClosedTotal float64     `json:"closed_total"`
	Records     []goldenRec `json:"records"`
}

func recKey(kind, idn, caseNo, typ, startSrc string, days int, owed, paid, behind float64) string {
	return fmt.Sprintf("%s|%s|%s|%d|%.2f|%.2f|%.2f|%s|%s",
		kind, idn, caseNo, days, owed, paid, behind, typ, startSrc)
}

func TestEMFeesParityWithSkill(t *testing.T) {
	goldenPath := filepath.Join("testdata", "emfees_golden.json")
	raw, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Skipf("golden file not present (%v)", err)
	}
	var gold goldenFile
	if err := json.Unmarshal(raw, &gold); err != nil {
		t.Fatalf("parse golden: %v", err)
	}

	path, cleanup := tempLookupDB(t)
	defer cleanup()
	d, err := Open(path)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer d.Close()

	asOf, _ := time.Parse("2006-01-02", gold.AsOf)
	res, err := EMFees(d, asOf)
	if err != nil {
		t.Fatalf("EMFees: %v", err)
	}

	if len(res.Open) != gold.OpenCount {
		t.Errorf("open count = %d, want %d", len(res.Open), gold.OpenCount)
	}
	if len(res.Closed) != gold.ClosedCount {
		t.Errorf("closed count = %d, want %d", len(res.Closed), gold.ClosedCount)
	}
	if got := round2(res.OpenTotal()); got != gold.OpenTotal {
		t.Errorf("open total = %.2f, want %.2f", got, gold.OpenTotal)
	}
	if got := round2(res.ClosedTotal()); got != gold.ClosedTotal {
		t.Errorf("closed total = %.2f, want %.2f", got, gold.ClosedTotal)
	}

	// Record-for-record comparison via canonical keys (order-independent).
	wantKeys := make([]string, 0, len(gold.Records))
	for _, r := range gold.Records {
		wantKeys = append(wantKeys, recKey(r.Kind, r.IDN, r.Case, r.Type, r.StartSrc, r.Days, r.Owed, r.Paid, r.Behind))
	}
	gotKeys := []string{}
	addAll := func(kind string, recs []emfees.Rec) {
		for _, r := range recs {
			gotKeys = append(gotKeys, recKey(kind, r.IDN, r.Case, r.Type, r.StartSrc, r.Days, r.Owed, r.Paid, r.Behind))
		}
	}
	addAll("open", res.Open)
	addAll("closed", res.Closed)

	sort.Strings(wantKeys)
	sort.Strings(gotKeys)
	if len(wantKeys) != len(gotKeys) {
		t.Fatalf("record count: got %d, want %d", len(gotKeys), len(wantKeys))
	}
	mismatches := 0
	for i := range wantKeys {
		if wantKeys[i] != gotKeys[i] {
			if mismatches < 10 {
				t.Errorf("record mismatch:\n  got  %s\n  want %s", gotKeys[i], wantKeys[i])
			}
			mismatches++
		}
	}
	if mismatches > 0 {
		t.Fatalf("%d record(s) diverged from the canonical skill", mismatches)
	}
}

func round2(f float64) float64 { return float64(int64(f*100+0.5)) / 100 }
